AWS_ACCESS_KEY_ID: 'AKIAIN2BPQPI4ZN4NDAA'
AWS_SECRET_ACCESS_KEY: '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'

development:
  SENDGRID_USERNAME: "app18327114@heroku.com"
  SENDGRID_PASSWORD: "j6k4e5ks"
  AWS_BUCKET: seucroch-bloccit-development
  FACEBOOK_ID: 510573235700643
  FACEBOOK_SECRET: 1a1cd1ad0b4a3e155bf3dbc823a9afd4

production:
  AWS_BUCKET: seucroch-bloccit-production
  FACEBOOK_ID: 171687789697808
  FACEBOOK_SECRET: 1ba53a630dadb2136535372ad6b6a2d6 
